name: workflow2

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  USER1: gagandeep
jobs:
  build:
     environment: dev
     env:
       USER2: sandeep
       USER1: sandeep_job
     runs-on: gagan-devops
     steps:
       - name: Checkout
         uses: actions/checkout@v4.1.1
       - name: step 2
         env:
           user3: ajit
           USER1: sandeep_step
         run: |
          ls -l
          echo "github repo name is ${{ GITHUB.REPOSITORY }} and branch name is ${{ GITHUB.REF_NAME }} "
          echo "Value for variable user1, user2 and user3 are $USER1 $USER2 $user3"
          echo " Value for user1 and servername are ${{ vars.user1 }} and ${{ vars.server_name }}"
          echo "password for env is ${{ secrets.token1 }} "
          echo " ${{ secrets.token1 }} " >> /tmp/gagan-pass
          pwd
          java -version
         if: github.event_name == 'pull_request'
       - run: echo " Print value of user 3 $user3"
  test:
     runs-on: gagan-devops
     if: runner.os == 'ubuntu'
     environment: prod
     steps:
       - name: Checkout
         uses: actions/checkout@v4.1.1
       - name: step 2
         run: |
          ls -l
          echo "github repo name is ${{ GITHUB.REPOSITORY }} and branch name is ${{ GITHUB.REF_NAME }} "
          echo " Value for user1 and servername are ${{ vars.user1 }} and ${{ vars.server_name }}"
          echo "password for env is ${{ secrets.token1 }} "
          echo " ${{ secrets.token1 }} " >> /tmp/gagan-pass
          echo " ${{ runner.os }} "
  deploy:
     runs-on: gagan-devops
     if: runner.os != 'ubuntu'
     steps:
       - name: Checkout
         uses: actions/checkout@v4.1.1
       - name: step 2
         run: |
          ls -l
          echo "github repo name is ${{ GITHUB.REPOSITORY }} and branch name is ${{ GITHUB.REF_NAME }} "
          echo " Value for user1 and servername are ${{ vars.user1 }} and ${{ vars.server_name }}"
          echo "password for env is ${{ secrets.token_repo }} "
          echo " ${{ secrets.token_repo }} " >> /tmp/gagan-pass
          echo " ${{ runner.os }} "
          cat /tmp/gagan-pass
  
  
