name: workflow2

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
     runs-on: ubuntu-latest
     steps:
       - run: |
          git clone https://github.com/admingagan/Maven-Project.git
          cd Maven-Project
          ls -l
          pwd
     
  
  
